version: '3.6'

services:

  mysql:
    build: .
    image: mysql
    platform: linux/amd64
    container_name: mysql_estudo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - app_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8088"
volumes:
  app_db:

networks:
  nt_mysql:
    driver: bridge